### ISSUE TITLE
Add support for MS Windows 7

### ISSUE THREAD

**Issue by gmacario** [gunnarx/franca_install_automation#22]
Hello,

I tried gunnarx/franca_install_automation with Vagrant running under MS Windows 7 and Cygwin.

As suggested I chose the supposedly stable "trusty64-lxde" branch. Here is the result I got:

```
gmacario@ITM-GMACARIO-W7 /cygdrive/e/data/GENIVI/franca_install_automation
$ vagrant up --provider=virtualbox
Vagrant has no proxy plugin => skipped proxy configuration.
Vagrant has no proxy plugin => skipped proxy configuration.
E:/data/GENIVI/franca_install_automation/Vagrantfile:42:in ``': No such file or directory - date +%Y%m%d%H%M (Errno::ENOENT)
        from E:/data/GENIVI/franca_install_automation/Vagrantfile:42:in `block in <top (required)>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/v2/loader.rb:37:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/v2/loader.rb:37:in `load'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:103:in `block (2 levels) in load'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:97:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:97:in `block in load'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:94:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:94:in `load'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/vagrantfile.rb:28:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:691:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:691:in `vagrantfile'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:441:in `host'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:207:in `block in action_runner'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:33:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:33:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:428:in `hook'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:673:in `unload'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/bin/vagrant:177:in `ensure in <main>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/bin/vagrant:177:in `<main>'

gmacario@ITM-GMACARIO-W7 /cygdrive/e/data/GENIVI/franca_install_automation
$
```

**Comment by gmacario** [comment]
FYI: You may get a detailed debugging log with all the steps I performed at
https://genivi-oss.atlassian.net/wiki/x/xwBJ (a login to GENIVI public wiki is required)

**Comment by gmacario** [comment]
Temporary workaround: https://github.com/gmacario/franca_install_automation/commit/c76962702daee8f1014a3d03fdd7ab912638609f

**Comment by gunnarx** [comment]
Keeping support for Windows as host  as "enhancement" for now.   :-)

**Comment by gmacario** [comment]
Submitted new PR https://github.com/gunnarx/franca_install_automation/pull/27 which is reported to work on:
- MS Windows 7, Cygwin64
- MS Windows 7, git version 2.6.0.windows.1

**Comment by gunnarx** [comment]
@gmacario  Ruby Time.strftime now merged.  Is everything OK now Gianpaolo?  
1. Can we confirm Windows support and close?
2. Does it still need cygwin or not?   If it does - do you think there is a way to avoid it?

**Comment by gmacario** [comment]
@gunnarx

> 1. Can we confirm Windows support and close?

Yes - just verified with master branch of https://github.com/gunnarx/franca_install_automation 

I have some additional cleanup in my fork that will submit as subsequent PR.
Anyway your master branch now works on Windows, so I am closing https://github.com/gunnarx/franca_install_automation/issues/22 

> 1. Does it still need cygwin or not? If it does - do you think there is a way to avoid it?

As reported earlier I tested PR #27 with
- MS Windows 7 64-bit, Cygwin64
- MS Windows 7 64-bit, git version 2.6.0.windows.1 (that includes Git Bash)

therefore Cygwin may be used but is not mandatory.

Hope that helps,
Gianpaolo
