### ISSUE TITLE
Add VIM syntax support for Franca

### ISSUE THREAD

**Issue by gunnarx** [gunnarx/franca_install_automation#28]
Add VIM syntax support for Franca.  Not really a major thing since editing is supposed to happen inside Eclipse.  Still, an idea I ran into when opening files using vi (vim) from the command shell.

**Comment by kbirken** [comment]
A remark regarding vim: A friendly user contributed some configuration files for Franca-specific highlighting with vim, see https://github.com/franca/franca/pull/192

This is available starting with Franca 0.11.0.

(I never tested this, but some people are using it and never complained :-) )

**Comment by gunnarx** [comment]
Cool.  This is better kept in the Franca repository just as you have.  I'll close this ticket.
