### ISSUE TITLE
Install fails when loading FRANCA_EXAMPLES_URL

### ISSUE THREAD

**Issue by gmacario** [gunnarx/franca_install_automation#33]
As of 2015-11-04 org_franca_examples_src_2015-07-29.zip is no longer
available in Google Drive (FRANCA_BASE_URL)

See also: https://github.com/franca/franca/issues/164

**Comment by gmacario** [comment]
See fix in PR https://github.com/gunnarx/franca_install_automation/pull/32

**Comment by gunnarx** [comment]
Merged PR.
