### ISSUE TITLE
Install CommonAPI 3.1

### ISSUE THREAD

**Issue by gunnarx** [gunnarx/franca_install_automation#8]
- Install eclipse packages needed for CommonAPI code generation
- Latest version now is 3.1.2
- Source: http://git.projects.genivi.org/?p=ipc/common-api-tools.git;a=summary

**Comment by kbirken** [comment]
I just implemented this locally, test is currently running :-). If this is successful, I can provide a pull request for this.

Note that CommonAPI 3.1.2 has a dependency on CDT. We have to ask Manfred if this is actually needed or some kind of accident. If it is required, then this is a strong argument for using the automotive Eclipse distro as a base.

**Comment by kbirken** [comment]
Remark: Combining CommonAPI 3.1.2 with Franca 0.9.2 doesn't make sense, because Franca 0.9.2 changed the deployment accessor generation and CommonAPI 3.1.2 contains some hardwired deployment accessors generated with Franca 0.9.1.

Thus, we either have to revert to Franca 0.9.1 here in order to combine it with CommonAPI 3.1.2 or wait for a new combination of Franca/CommonAPI.

**Comment by gunnarx** [comment]
Oops, I missed these comments.  I have also implemented and done the same - Franca 0.9.1 and CDT included.  For now it's DSL base + install CDT but as you indicate automotive base might be an alternative.  But then I'll need to do work on defining all the package names for the DSL stuff.
For the moment I guess it does not matter much?

**Comment by gunnarx** [comment]
Pushed branch cpp_common_api but it should be considered experimental, I have not tested a lot so far except that "Generate C++" with CommonAPI seemed to work.

**Comment by gunnarx** [comment]
cpp_common_api branch still a little funky, but seems to work in commit 2be5816b0e2 ...
I'll tag a release when I feel more confident.

**Comment by gunnarx** [comment]
Tagged and ready since a while back.

The README describes the branch you need to use cpp_common_api, to get this feature.

Can\t merge this to main branch(es) since those support Franca 0.10, and that's not possible in combination with CommonAPI.

Currently it is combined with Ubuntu trusty64-lxde variant.  
I think maybe reducing the different options in the future could make sense.
