### ISSUE TITLE
The Eclipse installation has two conflicting Xtend versions.

### ISSUE THREAD

**Issue by kbirken** [gunnarx/franca_install_automation#9]
The current provisioning produces an Eclipse installation which contains the plug-in "Xtend Core" in versions 2.0.0 and 2.7.3. The latter is correct, the former shouldn't be installed. This leads to problems when Xtend is used, e.g., for Franca transformations. 

Tested with branches precise64-lxde and automotive.

**Comment by gunnarx** [comment]
Klaus: Sorry I got lost on this one...  Do you know if this bug still there or is it already fixed it in the meantime?  Do you know which part pulls in the wrong version?

**Comment by kbirken** [comment]
I didn't check again, but I will and give you feedback...

**Comment by kbirken** [comment]
Now I checked. The plug-in org.eclipse.xtend with version number 2.0.0 (or 2.1.0 in 2015 installations) is the base for Xtend and Xtext 2.7.x and also Xpand, so it is perfectly normal. This is already part of the standard Eclipse distro and is not a result of the installation of Franca, CommonAPI etc.

Issue can be closed - false alarm.

**Comment by gunnarx** [comment]
OK, thanks.  Closing.
